import type { BagAction, GroupMeta, Pet, PetDetailMeta, PetGroup, PetStats, Skill } from '../types'

const petListImageMeta: Record<string, Pick<Pet, 'listImageOffsetX' | 'listImageOffsetY'>> = {
  谱尼: { listImageOffsetX: 0, listImageOffsetY: 0 },
  雷伊: { listImageOffsetX: 0, listImageOffsetY: 0 },
  盖亚: { listImageOffsetX: 0, listImageOffsetY: 0 },
  卡修斯: { listImageOffsetX: 0, listImageOffsetY: 0 },
  布莱克: { listImageOffsetX: 0, listImageOffsetY: 0 },
  缪斯: { listImageOffsetX: 0, listImageOffsetY: 0 },
  波克尔: { listImageOffsetX: 0, listImageOffsetY: 0 },
  派鲁基达: { listImageOffsetX: 0, listImageOffsetY: 0 },
  王之哈莫: { listImageOffsetX: 0, listImageOffsetY: 0 },
  提亚斯: { listImageOffsetX: 0, listImageOffsetY: 0 },
  嘟拉: { listImageOffsetX: 0, listImageOffsetY: 0 },
}

export const backpackPets: Pet[] = [
  {
    id: 1,
    name: '谱尼',
    level: 100,
    serial: '300',
    nature: '胆小',
    colorfulLevel: 0,
    requiredExp: 59996,
    totalExp: 1621367,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-puni.png',
    ...petListImageMeta['谱尼'],
    group: 'battle',
    learningPower: {
      attack: 1,
      specialAttack: 6,
      defense: 0,
      specialDefense: 1,
      speed: 254,
      hp: 248,
    },
  },
  {
    id: 2,
    name: '雷伊',
    level: 100,
    serial: '070',
    nature: '开朗',
    colorfulLevel: 1,
    requiredExp: 0,
    totalExp: 980320,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-leiyi.png',
    ...petListImageMeta['雷伊'],
    group: 'battle',
    learningPower: {
      attack: 255,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 3,
    name: '盖亚',
    level: 100,
    serial: '089',
    nature: '固执',
    colorfulLevel: 2,
    requiredExp: 0,
    totalExp: 936200,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-gaiya.png',
    ...petListImageMeta['盖亚'],
    group: 'battle',
    learningPower: {
      attack: 255,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 4,
    name: '卡修斯',
    level: 100,
    serial: '112',
    nature: '保守',
    colorfulLevel: 3,
    requiredExp: 0,
    totalExp: 902600,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-kaxiusi.png',
    ...petListImageMeta['卡修斯'],
    group: 'battle',
    learningPower: {
      attack: 0,
      specialAttack: 255,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 5,
    name: '布莱克',
    level: 100,
    serial: '118',
    nature: '冷静',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 901430,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-bulaike.png',
    ...petListImageMeta['布莱克'],
    group: 'battle',
    learningPower: {
      attack: 0,
      specialAttack: 255,
      defense: 0,
      specialDefense: 0,
      speed: 0,
      hp: 255,
    },
  },
  {
    id: 6,
    name: '缪斯',
    level: 100,
    serial: '124',
    nature: '胆小',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 889760,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-miusi.png',
    ...petListImageMeta['缪斯'],
    group: 'battle',
    learningPower: {
      attack: 0,
      specialAttack: 255,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 7,
    name: '波克尔',
    level: 100,
    serial: '068',
    nature: '急躁',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 601830,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-bokeer.png',
    ...petListImageMeta['波克尔'],
    group: 'standby',
    learningPower: {
      attack: 255,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 8,
    name: '派鲁基达',
    level: 47,
    serial: '1048',
    nature: '认真',
    colorfulLevel: 0,
    requiredExp: 744,
    totalExp: 321500,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-pailujida.png',
    ...petListImageMeta['派鲁基达'],
    group: 'standby',
    learningPower: {
      attack: 180,
      specialAttack: 0,
      defense: 60,
      specialDefense: 0,
      speed: 120,
      hp: 150,
    },
  },
  {
    id: 9,
    name: '王之哈莫',
    level: 100,
    serial: '3022',
    nature: '固执',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 1265300,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-wangzhihameng.png',
    ...petListImageMeta['王之哈莫'],
    group: 'standby',
    learningPower: {
      attack: 255,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 0,
      hp: 255,
    },
  },
  {
    id: 10,
    name: '提亚斯',
    level: 100,
    serial: '176',
    nature: '开朗',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 531980,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-tiyasi.png',
    ...petListImageMeta['提亚斯'],
    group: 'standby',
    learningPower: {
      attack: 0,
      specialAttack: 255,
      defense: 0,
      specialDefense: 0,
      speed: 255,
      hp: 0,
    },
  },
  {
    id: 11,
    name: '嘟拉',
    level: 0,
    serial: '201',
    nature: '认真',
    colorfulLevel: 0,
    requiredExp: 120,
    totalExp: 0,
    acquiredAt: '2026-4-28',
    image: '/backpack/pets/full-dula.png',
    ...petListImageMeta['嘟拉'],
    group: 'standby',
    learningPower: {
      attack: 0,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 0,
      hp: 128,
    },
  },
  {
    id: 12,
    name: '',
    level: 0,
    serial: '000',
    nature: '未设置',
    colorfulLevel: 0,
    requiredExp: 0,
    totalExp: 0,
    acquiredAt: '',
    image: '',
    group: 'standby',
    learningPower: {
      attack: 0,
      specialAttack: 0,
      defense: 0,
      specialDefense: 0,
      speed: 0,
      hp: 0,
    },
    isEmpty: true,
  },
]

export const petGroups: PetGroup[] = ['battle', 'standby']

export const groupMeta: Record<PetGroup, GroupMeta> = {
  battle: {
    title: '出战精灵',
    countLabel: '首发阵容',
  },
  standby: {
    title: '备战精灵',
    countLabel: '候补队列',
  },
}

export const statsByName: Record<string, PetStats> = {
  谱尼: { attack: 152, specialAttack: 125, defense: 103, specialDefense: 103, speed: 174, hp: 239 },
  雷伊: { attack: 153, specialAttack: 104, defense: 92, specialDefense: 94, speed: 181, hp: 256 },
  盖亚: { attack: 168, specialAttack: 84, defense: 116, specialDefense: 92, speed: 145, hp: 268 },
  卡修斯: { attack: 149, specialAttack: 111, defense: 103, specialDefense: 103, speed: 163, hp: 248 },
  布莱克: { attack: 151, specialAttack: 112, defense: 98, specialDefense: 103, speed: 170, hp: 245 },
  缪斯: { attack: 126, specialAttack: 148, defense: 106, specialDefense: 108, speed: 156, hp: 252 },
  波克尔: { attack: 98, specialAttack: 84, defense: 76, specialDefense: 73, speed: 120, hp: 182 },
  派鲁基达: { attack: 131, specialAttack: 108, defense: 101, specialDefense: 95, speed: 132, hp: 224 },
  王之哈莫: { attack: 162, specialAttack: 96, defense: 121, specialDefense: 118, speed: 138, hp: 294 },
  提亚斯: { attack: 91, specialAttack: 135, defense: 80, specialDefense: 104, speed: 148, hp: 216 },
  嘟拉: { attack: 60, specialAttack: 49, defense: 52, specialDefense: 48, speed: 40, hp: 120 },
}

export const skillBook: Record<string, Skill[]> = {
  谱尼: [
    { name: '千烈虚光闪', power: 140, pp: '10/10', tone: 'light' },
    { name: '虚无', power: 0, pp: '1/1', tone: 'water' },
    { name: '圣灵魔闪光', power: 160, pp: '5/5', tone: 'light' },
    { name: '灵魂干涉', power: 0, pp: '20/20', tone: 'water' },
  ],
  雷伊: [
    { name: '惊雷切', power: 95, pp: '25/25', tone: 'light' },
    { name: '雷祭', power: 0, pp: '5/5', tone: 'water' },
    { name: '霹雳风暴', power: 150, pp: '10/10', tone: 'light' },
    { name: '瞬雷天闪', power: 0, pp: '20/20', tone: 'water' },
  ],
  盖亚: [
    { name: '破元闪', power: 120, pp: '10/10', tone: 'fire' },
    { name: '返璞归真', power: 0, pp: '5/5', tone: 'water' },
    { name: '日月皆伤', power: 140, pp: '10/10', tone: 'fire' },
    { name: '战神狂怒', power: 0, pp: '20/20', tone: 'water' },
  ],
}

export const fallbackSkills: Skill[] = [
  { name: '火环', power: 55, pp: '35/35', tone: 'fire' },
  { name: '凝目而视', power: 0, pp: '15/15', tone: 'water' },
  { name: '猛击', power: 60, pp: '30/30', tone: 'fire' },
  { name: '极速', power: 0, pp: '30/30', tone: 'water' },
]

export const bagActions: BagAction[] = Array.from({ length: 6 }, (_, index) => {
  const id = index + 1

  return {
    id,
    label: `功能 ${id}`,
    icon: `/backpack/icons/${id}.png`,
  }
})

export const petDetailMeta: PetDetailMeta = {
  evolutionLabel: '无法进化',
  elementalIcon: '/backpack/elem/shengling.png',
}
